### ISSUE TITLE
Possible to use name instead id?

### ISSUE THREAD

**Issue by gisu** [qcam/3llo#15]
Because is not very easy to copy the id in a tmux pane with mouse. Easier is to use the Name.

**Comment by qcam** [comment]
@gisu yeah it has been bugging me for a while too.

I have something in my mind that instead of showing real Trello IDs (which requires annoying copy-and-paste and mouses), let's assign them to our own IDs.

```
 3llo  > card list mine

[C1] - (Current Week) - Task A
[C2] - (Current Week) - Task B
[C3] - (Current Week) - Task C
[C4] - (In Progress) - Task D
[C5] - (Shipping) - Task E
```

where `C` stands for "card" and IDs are numbers that increases sequentially, the same would apply to lists and boards and such.

So to get card/list info.

```
card show C1
list cards L1
```

How does this approach sound to you?

**Comment by gisu** [comment]
It sounds nice.

**Comment by several27** [comment]
Just an idea:

It might be even cooler if you could use those "ids" without typing out the full command. I reckon it should be obvious that as long as ids are unique (at least for previously listed stuff) just using them will display their "contents" E.g.

```
3llo  > list list

[L1] - First List
[L2] - Second List

3llo  > L2
[ ] C1] - Item on the second list
```

**Comment by qcam** [comment]
@several27 this sounds very interesting!

**Comment by sauloperez** [comment]
https://github.com/Morantron/tmux-fingers might be of help @gisu. I'd also like to use this feature though.

**Comment by brasilikum** [comment]
How about just autocompleting the ids and accepting an id as soon as it's unique (like docker cli does)?
