### ISSUE TITLE
Run commands from the bash command line (and not the 3llo "shell")?

### ISSUE THREAD

**Issue by johnnyutahh** [qcam/3llo#38]
How can I do this?

`$ 3llo card list | grep animation`

For me, the main value of a command-line tool is that at I can combine it (through pipes, among other things) with other command-line tools. But if one can only run `3llo` through it's own interactive "shell," then I do not have any options to do this.

In such a case, the `3llo` is not that usable for me, very unfortunately. (Because the installation was a breeze.)  😕

**Comment by johnnyutahh** [comment]
My system environment below. I (also) can not yet find a way to print the version of `3llo`.

`$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G6030
$ 3llo --version


    3llo - CLI for Trello

    Usage:
    board list                   - Show list of board
    board select                 - Select board
    card list                    - Show list of cards grouped by list
    card list mine               - Show list of my cards
    card add                     - Create a card
    card show <card_id>          - Show card information
    card move <card_id>          - Move card to a list
    card self-assign <card_id>   - Self-assign a card
    card assign <card_id>        - Assign a user to a card
    card comments <card_id>      - Load recent comments of a card
    card comment <card_id>       - Add a comment to a card
    card archive <card_id>       - Archive a card
    list list                    - Show all lists
    list cards <list_id>         - Show all cards in list
    list archive-cards <list_id> - Archive all cards in list
    help                         - Show help menu
    exit                         - Exit program
        

 3llo  > 
`

**Comment by qcam** [comment]
@johnnyutahh Thanks for the great suggestion. 3llo was designed as a standalone interactive tool (and always will be). I don't think there's any easy way to support this soon.

As a suggestion, I could imagine we can add extra support for this in a command pipelining way. For example:

```
3llo exec board select b1234, card list, card self-assign c56745 | grep ...
```

However, a big re-design might be needed since the current codes are only to support interactive tool.

I would also suggest you to check out https://github.com/mheap/trello-cli. It might already work the way you want.
